name: py35
dependencies:
- pip=9.0.1=py35_0
- python=3.5.2=0
- setuptools=20.3=py35_0
- wheel=0.29.0=py35_0
- pip:
  - blessings==1.6
  - click==6.7
  - whistle==1.0a3
  - first==2.0.1
  - jinja2==2.9.6
  - markupsafe==1.0
  - pbr==3.1.1
  - pip-tools==1.10.1
  - six==1.11.0
  - stevedore==1.27.1
  - tornado==4.5.2
  - yapf==0.19.0
